<?php

namespace Products;


abstract class Products
{
    private $price;
    private $skidka;
    private $ves;


    /**
     * @return mixed
     */
    public function getSkidka($skidka)
    {
        return $this->skidka = $skidka;
    }


    /**
     * @return mixed
     */
    public function getVes($ves)
    {
        return $this->ves = $ves;
    }

    /**
     * @return mixed
     */
    public function getPrice($price)
    {
        return $this->price = $price;
    }


    public  function type()
    {
        return null;
    }

    public function view()
    {
        if (($this->skidka == 1) || ($this->ves >= 10)) {
            $this->price = $this->price * $this->ves * 0.1 + 250;
            echo 'Ваш заказ: ' . $this->price . '.руб, С учетом доставки 250 ';
        } else {
            $this->price = $this->price * $this->ves + 300;
            echo 'Ваш заказ: ' . $this->price . '.руб, С учетом доставки 300 ';

        }

    }




}


class Apple extends Products
{
    public function type()
    {
        parent::type(); // TODO: Change the autogenerated stub

        echo  'It`Apple';
        echo '<br/>';
    }

}

class Cheri extends Products
{
    public function type()
    {
        parent::type(); // TODO: Change the autogenerated stub

        echo  'It`s Cheri';
        echo '<br/>';
    }

}
